Bootstrap: docker
From: rockylinux:9.3.20231119

%environment
    LC_ALL=C

%post
    dnf -y update
    dnf -y upgrade
    dnf install -y epel-release java-21-openjdk wget procps

    JAVA_HOME=/usr/lib/jvm/jre-21-openjdk

    FUSEKI_VERSION=4.10.0
    FUSEKI_INSTALL_DIR=/opt
    FUSEKI_HOME=/opt/fuseki
    FUSEKI_BASE=/etc/fuseki
    FUSEKI_DB=/etc/fuseki_db

    # Download and extract Fuseki
    wget https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-${FUSEKI_VERSION}.tar.gz
    tar xzf apache-jena-fuseki-${FUSEKI_VERSION}.tar.gz -C $FUSEKI_INSTALL_DIR
    mv ${FUSEKI_INSTALL_DIR}/apache-jena-fuseki-${FUSEKI_VERSION} ${FUSEKI_INSTALL_DIR}/fuseki

    # FUSEKI_CONF will later bind the configuration files and the keystore into the container.
    mkdir -p ${FUSEKI_BASE}

    # FUSEKI_DB will later bind the host dir for storing the database.
    mkdir -p ${FUSEKI_DB}
  
    # Tidy up
    rm apache-jena-fuseki-${FUSEKI_VERSION}.tar.gz
    dnf clean all

%test

%environment
    export JAVA_HOME=/usr/lib/jvm/jre-21-openjdk
    export FUSEKI_HOME=/opt/fuseki
    export FUSEKI_BASE=/etc/fuseki
    export FUSEKI_DB=/etc/fuseki_db

%runscript
    #TODO Run with configuration but with test data?

%startscript
    export JVM_ARGS=-Xmx4G
    /opt/fuseki/fuseki-server --jetty-config=/etc/fuseki/fuseki-jetty-https.xml

%labels

%help
    
