version: "2.0"
instances:
  haproxy:
    build:
      context: ./haproxy
    network:
      enable: false
    ports:
      - 80:80
      - 443:443

  fuseki:
    build:
      context: ./fuseki
    volumes:
      - ./fuseki/etc_fuseki:/etc/fuseki
      - ./db:/etc/fuseki_db
    network:
      enable: false
    ports:
      - 3030:3030
      
